FROM andrewseidl/nvidia-cuda:10.2-base-ubuntu20.04

MAINTAINER Daniel Franco-Barranco "daniel.franco@dipc.org"

ARG DEBIAN_FRONTEND=noninteractiveS
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A4B469963BF863CC
RUN apt-get update && apt-get install -y \
    wget \
    ffmpeg \
    libsm6 \
    libxext6 \
	git

# Download and prepare conda
RUN wget -q -P /tmp \
    https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && mkdir /installations && bash /tmp/Miniconda3-latest-Linux-x86_64.sh -b -p /installations/miniconda3 \
    && rm /tmp/Miniconda3-latest-Linux-x86_64.sh \
    && echo "export PATH="/installations/miniconda3/bin:$PATH"" >> ~/.bashrc \
    && /bin/bash -c "source ~/.bashrc"
ENV PATH /installations/miniconda3/bin:$PATH
RUN conda update --all

# Create the environment
ENV PATH="/opt/conda/bin:$PATH"
RUN . /installations/miniconda3/etc/profile.d/conda.sh
RUN conda update -qy conda \
    && conda create -n BiaPy_env python=3.10 \
    && conda init bash

# Set up shell to use the created env
SHELL ["conda", "run", "-n", "BiaPy_env", "/bin/bash", "-c"]

# Install BiaPy
RUN pip install biapy==3.5.4

# Install Pytorch 1.12.1 + CUDA 10.2
RUN conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=10.2 -c pytorch
RUN pip install timm pytorch-msssim torchmetrics[image]

# Clone BiaPy, as running it with python -c "" stops the container with no error after a few seconds running
RUN git clone --depth 1 https://github.com/BiaPyX/BiaPy.git  --branch v3.5.4 /installations/BiaPy
# This time clone the last commit (25729c ; v3.5.2) as some minor bugs were solved but not created a new release yet
# RUN git clone --depth 1 https://github.com/BiaPyX/BiaPy.git /installations/BiaPy

# User home directory
RUN mkdir -p /home/user
ENV HOME /home/user
RUN echo 'export HOME=/home/user' >> ~/.bashrc

# To remove CuDNN issue 
WORKDIR /installations/miniconda3/envs/BiaPy_env/lib/python3.10/site-packages/nvidia/cuda_nvrtc/lib/
RUN ln -s libnvrtc.so.11.2 libnvrtc.so

ENTRYPOINT ["conda", "run", "--no-capture-output", "-n", "BiaPy_env", "python3", "-u", "/installations/BiaPy/main.py"]
# ENTRYPOINT ["conda", "run", "--no-capture-output", "-n", "BiaPy_env", "python3", "-u", "-c", "from biapy import BiaPy; BiaPy(..)"]
