name: Publish Docker image

on:
  release:
    types: [published]
  # workflow_run:
  #   workflows: ['Upload BiaPy to PyPI']
  #   types: [completed]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: biapyx/biapy
          flavor: |
            latest=auto
            prefix=
            suffix=-11.8,onlatest=false

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: biapyx
          password: ${{ secrets.BIAPYX_DOCKERHUB_PASS }}
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./biapy/utils/env/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ steps.meta.outputs.tags }}
