name: Upload BiaPy to PyPI

on:
  release:
    types: [published]

jobs:
  pypi-publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/biapy
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip" # caching pip dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel build twine
      - name: Build package
        run: |
          python -m build 
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
      - name: Trigger bump workflow and wait
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: BiaPyX
          repo: BiaPy
          github_token: ${{ secrets.GITHUB_TOKEN }}   # or a PAT if cross-repo
          workflow_file_name: conda-forge-bump.yml
          ref: master
          wait_interval: 60
